---
- import_playbook: ./prometheus.yml
- import_playbook: ./alertmanager.yml
- import_playbook: ./grafana.yml
- import_playbook: ./node-exporter.yml
- import_playbook: ./mysqld-exporter.yml
- import_playbook: ./blackbox-exporter.yml
- import_playbook: ./nginx.yml
- import_playbook: ./users.yml
- import_playbook: ./fluentd.yml
- import_playbook: ./vim.yml
- import_playbook: ./firewalld.yml
- import_playbook: ./openjdk.yml
- import_playbook: ./pip.yml
- import_playbook: ./postgresql_yum.yml
- import_playbook: ./sonar.yml
- import_playbook: ./terraform.yml
